apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: micheal-apps
  namespace: argocd
spec:
  description: Project for micheal applications
  sourceRepos:
  - 'https://github.com/michealL682/terraform-aws-eks-argocd.git'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
